bot:
  name: ${BOT_NAME:family-bot}
  token: ${BOT_TOKEN}

environment:
  logback-folder-path: ${LOGBACK_FOLDER_PATH:./logs}
spring:
  application:
    name: family-bot
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: ${DATABASE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
  cloud:
    openfeign:
      client:
        config:
          recipes-service:
            connect-timeout: ${RECIPES_SERVICE_TIMEOUT:10000}
            read-timeout: ${RECIPES_SERVICE_TIMEOUT:10000}
            logger-level: full
          purchases-service:
            connect-timeout: ${PURCHASES_SERVICE_TIMEOUT:10000}
            read-timeout: ${PURCHASES_SERVICE_TIMEOUT:10000}
            logger-level: full
  jackson:
    default-property-inclusion: non_null

external-service:
  recipes:
    host: ${RECIPES_SERVICE_HOST:http://recipes-app-svc:8080}
  purchases:
    host: ${PURCHASES_SERVICE_HOST:http://purchases-analyzer-svc:8080}

logging:
  level:
    org.hibernate.sql: ${SQL_LOGGING_LEVEL:INFO}
    org.hibernate.orm.jdbc.bind: ${SQL_BIND_LOGGING_LEVEL:INFO}
    root: ${LOGGING_LEVEL:INFO}
    org.zalando.logbook: ${LOGBOOK_LEVEL:TRACE}
    http.logbook: ${HTTP_LOGBOOK_LEVEL:INFO}

logbook:
  format.style: http
  filter.enabled: true
  predicate:
    include:
      - path: /**