name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for deploy (format: build number, e.g.: 1.0.0-1)'
        required: true
        type: string
        default: '1.0.0-1'
      environment:
        description: 'Environment for deployment'
        required: true
        type: choice
        options:
          - test
          - production
        default: 'production'
      config_repo:
        description: 'repository with configs'
        required: true
        type: string
        default: 'kamar4k/deploy-configurations'

jobs:
  deploy:
    uses: kamar4k/pipelines/.github/workflows/common-deploy.yml@cd
    with:
      service: recipes-bot
      version: ${{ github.event.inputs.version }}
      environment: ${{ github.event.inputs.environment }}
      config_repo: ${{ github.event.inputs.config_repo }}
      config_path: ""  # или путь, если конфиги лежат в поддиректории
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}